// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_Final.Data;

#nullable disable

namespace Proiect_Final.Migrations
{
    [DbContext(typeof(Proiect_FinalContext))]
    [Migration("20221227205954_Chelnerupdate")]
    partial class Chelnerupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Proiect_Final.Models.Chelner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeChelner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Chelner");
                });

            modelBuilder.Entity("Proiect_Final.Models.Rezervare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("ChelnerID")
                        .HasColumnType("int");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRezervare")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumarPersoane")
                        .HasColumnType("int");

                    b.Property<string>("NumeRestaurant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ChelnerID");

                    b.ToTable("Rezervare");
                });

            modelBuilder.Entity("Proiect_Final.Models.Rezervare", b =>
                {
                    b.HasOne("Proiect_Final.Models.Chelner", "Chelner")
                        .WithMany("Rezervari")
                        .HasForeignKey("ChelnerID");

                    b.Navigation("Chelner");
                });

            modelBuilder.Entity("Proiect_Final.Models.Chelner", b =>
                {
                    b.Navigation("Rezervari");
                });
#pragma warning restore 612, 618
        }
    }
}
